language: node_js
node_js:
- '4.1'
before_script:
- npm install -g gulp
script:
- gulp bump
- gulp
deploy:
  provider: npm
  skip_cleanup: true
  email: developers@acklenavenue.com
  api_key:
    secure: V0Q0+Z/A/oIT7OFhXA5g3O6tqdpKAcV1aPMmp8lI+xdGdzldA63vj9YiHA/K3U1zxtSRRaoLG5IpLxtcLCCyMDYHchNbbjaYGH8VoC3qBDcA1+ZUSCGawFwVyRjtAxRjbBgJmjyKMHkqbvWvYotdotJ/reLDWqCCz2nHcYMorXX9SeMFhwUxfi/d7Z2EHKue1RjA5ABkuraWMMQLQb69EOTjTyQDbXa8TqtaOqP/ZuwNy42U46nZZ/mKw/wr1yfilhDq+JmkVBSyMMqT4OCa5Mob1l0IVGdn22k79OW6clVniRKpWnvqT4Gmgybfpv3kk0LEAIDEPhJJT2sXOnwYVHRZSiaCH3QfqwusBYDeccXXcE42wFBLBFR2+bpPWU285dG1krZ9HU2eak9u8N6xOoXcsbdR/KiKDaZW+WHoBpdVlSNZzVs69OIETQIypzbUiWMWk7khMR/aRPO3l+h539pTgJTd8e/dv5uCjfPNmsIncBNYbniguvKNHbQXioPRrke6kMRXUMUkTVLr4KBihEp5P36hK97oly7lMQUs3dT+owp7ICN5Np9siOfgSzG3DMHZVBeLgDjMCPQ8TnkTLkukPZ7tZybhGbf3U8QIRD+3ZgYktoJSgQWaAaiScAHqC3edBphw0LK/TYObVL908Ojbv+WLvjncm0P7xxIaxTo=
  on:
    tags: false
    repo: AcklenAvenue/pepino-lib
    branch: develop